---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: app-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - name: analytics
        image: metabase/metabase:latest
        ports:
        - name: http
          containerPort: 3000
        env:
          - name: PATH
            value: "/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          - name: LANG
            value: "en_US.UTF-8"
          - name: LANGUAGE
            value: "en_US:en"
          - name: LC_ALL
            value: "en_US.UTF-8"
          - name: JAVA_VERSION
            value: "jdk-11.0.7+10"
          - name: JAVA_HOME
            value: "/opt/java/openjdk"
          - name: FC_LANG
            value: "en-US"
          - name: LC_TYPE
            value: "en_US.UTF-8"
          - name: JAVA_TIMEZONE
            value: "US/Central"
          - name: MB_DB_FILE
            value: "/metabase-data/metabase.db"
          - name: VIRTUAL_HOST
            value: "analytics.caresherpa.us"
          - name: VIRTUAL_PORT
            value: "3000"
        volumeMounts:
          - name: analytics-db
            mountPath: /metabase-data
      volumes:
      - name: analytics-db
        persistentVolumeClaim:
          claimName: analytics-pvc