---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: map
  namespace: app-map
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: map
    spec:
      containers:
      - name: map
        image: us-central1-docker.pkg.dev/caresherpaprod/cs-docker/cm:test
        ports:
        - name: http
          containerPort: 80
