apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
    name: managed-cert-k8s
    namespace: emissary
spec:
  domains:
  - analytics-k8s.caresherpa.us
  - expedition-k8s.caresherpa.us
  - map-k8s.caresherpa.us