---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: http-listener-8080
  namespace: emissary
spec:
  port: 8080
  protocol: HTTPS
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL