name: Mirror to caresherpa

on:
  push:
    branches:
      - main
      - dev-infrastructure
      - security-improvements
      - initial_infra
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: Mirror repository to caresherpa organization
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.MIRROR_TOKEN }}

      - name: Mirror to caresherpa/infrastructure
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: https://github.com/caresherpa/infrastructure.git
          ssh_private_key: ${{ secrets.MIRROR_SSH_KEY }}